export const products = [
  {
    id: 1,
    img: '/images/h3.svg',
    name: 'butter',
    desc: 'เนยจืด นำเข้าจากดาวเสาร์',
    price: ' 100',
  },
  {
    id: 2,
    img: '/images/h2.svg',
    name: 'beef',
    desc: 'เนื้อสเต็กชั้นดี พรีเมี่ยม',
    price: ' 100',
  },
  {
    id: 3,
    img: '/images/honey.svg',
    name: 'honey',
    desc: 'น้ำผึ้งเดือน5ยกกำลัง5',
    price: ' 100',
  },
  {
    id: 4,
    img: '/images/oil.png',
    name: 'Olive oil',
    desc: 'น้ำผึ้งเดือน5ยกกำลัง5',
    price: ' 100',
  },
  {
    id: 5,
    img: '/images/salt.png',
    name: 'Salt',
    desc: 'น้ำผึ้งเดือน5ยกกำลัง5',
    price: ' 100',
  },
  {
    id: 6,
    img: '/images/pepper.png',
    name: 'Peeper',
    desc: 'น้ำผึ้งเดือน5ยกกำลัง5',
    price: ' 100',
  },
  {
    id: 7,
    img: '/images/h1.svg',
    name: 'honey',
    desc: 'น้ำผึ้งเดือน5ยกกำลัง5',
    price: ' 100',
  },
  {
    id: 8,
    img: '/images/h4.svg',
    name: 'honey',
    desc: 'น้ำผึ้งเดือน5ยกกำลัง5',
    price: ' 100',
  },
  {
    id: 9,
    img: '/images/h5.svg',
    name: 'soy soce',
    desc: 'น้ำผึ้งเดือน5ยกกำลัง5',
    price: ' 100',
  },
];
